### ISSUE TITLE
Handle links in notifications?

### ISSUE THREAD

**Issue by andylash** [gfk-ba/meteor-notifications#16]
I use info notifications for server communication.  I sometimes put links in there.  To make this work I need to change notification.html to have {{{message}}} instead of {{message}}.  Also click anywhere to close is too easy to get wrong, so I just allow click on the X to close instead.  I'm curious if others have used this library in this way and have thoughts around the best way to change it to support this case (or if it even should).

**Comment by marcodejongh** [comment]
Fixed with #20 & #19
