### ISSUE TITLE
Notifications is undefined

### ISSUE THREAD

**Issue by Visudare** [gfk-ba/meteor-notifications#22]
When trying to set default settings the server gets an error: "Notifications is not defined". As in your example I put the code into the Meteor.startup(); Method but here it seems that Notification is not defined for server.

Example:

/server/env.js

Meteor.startup({
            _.extend(Notifications.defaultOptions, {
	        timeout: 2500
	    });
});

**Comment by marcodejongh** [comment]
@Visudare Notifications is a client side package. So you should set the defaultOptions on the clientside.

**Comment by Visudare** [comment]
Oh *** ... I am sorry. I am an idiot. I thought Meteor.startup() is jsut a server thing. THis was my fault - sorry for this and thanks for the fast response!
