### ISSUE TITLE
Can you call a notification from the server? 

### ISSUE THREAD

**Issue by almogdesign** [gfk-ba/meteor-notifications#24]
I'm trying to call a notification from the server and I'm getting the following error I take it it's not supported. 

TypeError: Object [object Object] has no method 'success'

**Comment by marcodejongh** [comment]
@almogdesign Notifications is a client side package.
Maybe https://atmospherejs.com/yogiben/notifications is more what you ar elooking for

**Comment by almogdesign** [comment]
Thanks
