### ISSUE TITLE
Changing Animation

### ISSUE THREAD

**Issue by sangyoo91** [gfk-ba/meteor-notifications#28]
Could you nudge me in the right direction,
or tell me where to edit to change the animations?

My notifications flicker before showing for some reason..

**Comment by marcodejongh** [comment]
@sangyoo91 flickering should not happen please submit a reproduction path for it so I can look in to it.

All the animation code happens [here](https://github.com/gfk-ba/meteor-notifications/blob/master/notifications.js#L267-L285).

**Comment by marcodejongh** [comment]
If this is still a problem please reopen the issue
