### ISSUE TITLE
notifications do not stay visible when scrolling

### ISSUE THREAD

**Issue by oshai** [gfk-ba/meteor-notifications#32]
the notifications are visible when they first show up, on the top left. then when I scroll down, I don't see them anymore.
here is a picture:
![image](https://cloud.githubusercontent.com/assets/2683969/8023684/d71dedd8-0d1e-11e5-823f-99e1611fb657.png)

similarly, when the page is scrolled down and a notification appear, it is not displayed unless the page is scrolled back up. is there an option to control that? css maybe?

**Comment by oshai** [comment]
this is a solution for that:
    ul.notifications {
      position: fixed;
    }

but if that is correct, I think it should be the default.

**Comment by marcodejongh** [comment]
@oshai It depends on how you want your application to look.
Sorry for my late reply I was away on vacation this was already discussed before here: https://github.com/gfk-ba/meteor-notifications/issues/3.

I will add a FAQ in the readme.md about how to make it fixed
