### ISSUE TITLE
Push notification from server side

### ISSUE THREAD

**Issue by farald** [gfk-ba/meteor-notifications#34]
Is there a simple-ish way to push a notification from the server side to the client?

**Comment by JacobPariseau** [comment]
Create a collection to hold your notifications and let your user subscribe to it. Then on the client, observe for added documents. When a document is added, display with this package. All you need do from the server is insert a document to the collection.

**Comment by marcodejongh** [comment]
@farald What @JacobPariseau said is a good option. I added a example of what this would look like. Take in mind though this is a naive implementation and it leaves a lot questions unanswered.

Shared:
```
var ServerNotification = new Meteor.Collection('servernotifications');
```

Server:
```
Meteor.publish('serverNotifications', function () {
  return ServerNotification.find();
});
```

Client:
```
  Meteor.subscribe('servernotifications');
  ServerNotification.find().observeChanges({
    added: function(id, doc) {
       Notifications.success('Server notification', doc.message);
    }
  });
```

**Comment by Levino** [comment]
@marcodejongh Correction:

Shared:
```
ServerNotification = new Mongo.Collection('servernotifications');
```
Server (only sending notifications to a specific user):
```
Meteor.publish('servernotifications', function () {
  return ServerNotification.find({userId: this.userId});
});
```
Client:
```
  Meteor.subscribe('servernotifications');
  ServerNotification.find().observeChanges({
    added: function(id, doc) {
       Notifications.success('Server notification', doc.message);
    }
  });
```

**Comment by marcodejongh** [comment]
:+1:  Thx

**Comment by Levino** [comment]
Is there really no package for this? I am tempted to write one...

**Comment by marcodejongh** [comment]
@Levino @farald I just created a [package](https://github.com/gfk-ba/meteor-server-messages) which does this but it's re-usable for other purposes.

Since I get a lot of questions on how to push notifications from the server to the client I used that use-case for the [example page](server-messages-example.meteor.com) [repository](https://github.com/gfk-ba/meteor-server-messages-example).
